version: '2'

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/reis:/data"

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"