version: '2'

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  cache:
    build: ./docker/redis
    ports:
      - "6379:6379"
      # 6380:ローカル向けhttp通信用ポート
      - "6380:6380"
    environment:
      REDIS_PASSWORD: "password"

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"